services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7777:7777
    image: primy-movie-backend-image
    container_name: primy-movie-backend-container
    env_file:
      - .env
    volumes:
      - ./src:/app/src/
