service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-east-1
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/index.handler # highlight-line
    events:
      - httpApi:
          path: /graphql
          method: POST
